### ISSUE TITLE
Issue with env variables with Docker

### ISSUE THREAD

**Issue by mjp0** [Kaciras/ts-directly#2]
I'm not sure why but for some reason when I use this to run code inside a Docker container, it doesn't have access to the env variables I'm passing to Docker. The issue seems to exist only when executed inside a container.

Here's how I set the env for test: `docker run -it --env-file ./.env -p 4000:4000 local/tstest`

Any ideas?

**Comment by Kaciras** [comment]
Thanks for reporting this issue. I can't determine if it's this package or something else broken, could you provide a minimal reproducible example?

**Comment by mjp0** [comment]
Ok, had time to debug this further. Turns out this is a very weird issue with dotenv package. Envs work perfectly with node + ts-directly when run local, and with Bun in docker container also, but with node + ts-directly in docker container dotenv suddenly doesn't get env variables and I need to read from `process.env`.

Anyways, false alarm and this is resolved :)
